### ISSUE TITLE
'TfPoseEstimator' object has no attribute 'persistent_sess'

### ISSUE THREAD

**Issue by garybruckheimer** [ildoonet/tf-pose-estimation#64]
I was able to run the mobilenet model without any problems with the webcam demo.

cmd (works!!)
python3 src/run_webcam.py --model mobilenet_thin_432x368 --camera 0

cmd (doenst work) 
python3 src/run_webcam.py --model cmu_640x480 --camera 0
python3.5 src/run_webcam.py --model cmu_640x480 --camera 0
python3.6 src/run_webcam.py --model cmu_640x480 --camera 0

cmu modell 640x480 is not working as well cmu_640x360 also not working.
Anyone had the same issue and found a fix?

Traceback (most recent call last):
  File "src/run_webcam.py", line 33, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
  File "/opt//tf-pose-estimation/src/estimator.py", line 257, in __init__
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
Exception ignored in: <bound method TfPoseEstimator.__del__ of <estimator.TfPoseEstimator object at 0x7fb5ad439eb8>>
Traceback (most recent call last):
  File "/opt//tf-pose-estimation/src/estimator.py", line 280, in __del__
    self.persistent_sess.close()
AttributeError: 'TfPoseEstimator' object has no attribute 'persistent_sess'

**Comment by leighton** [comment]
@garybruckheimer, this is to do with the download.sh scripts, see PR #65

**Comment by ildoonet** [comment]
@leighton Thanks, I merged it. I accidentally upload wrong path.

**Comment by MoonBunnyZZZ** [comment]
I use the two new version download.sh files for cmu_640x360&cmu_640x480, which were downloaded Feb 5.But this problem still occur.I check the local .sh file with the repo,and it seems like same with each other.So I don't know why.Please help me. @leighton @ildoonet 

`(tf) 14:39:34@~/Desktop/pafs-2/src$ python run.py --model=cmu_640x360 --image=../images/005808361.jpg                  
/home/moon/miniconda3/envs/tf/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "run.py", line 35, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
  File "/home/moon/Desktop/pafs-2/src/estimator.py", line 258, in __init__
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
Exception ignored in: <bound method TfPoseEstimator.__del__ of <estimator.TfPoseEstimator object at 0x7fe53289b438>>
Traceback (most recent call last):
  File "/home/moon/Desktop/pafs-2/src/estimator.py", line 281, in __del__
    self.persistent_sess.close()
AttributeError: 'TfPoseEstimator' object has no attribute 'persistent_sess'
`

**Comment by leighton** [comment]
@MoonBunnyZZZ, @ildoonet: seems like the binary download links are dynamic not static. I've modified the download scripts to scrape the binary download links #83.

**Comment by MoonBunnyZZZ** [comment]
@leighton Thank you very much for your help! I use the cmu model to have a test on image/apink1_crop.jpg file,by 'python src/run.py --model=cmu '.The inference process takes 5 seconds.The jpg file is 500*500 pixels.It seems like not so realtime estimation.May I consult you about how to use GPU to accelerate。
